# Generated by Django 5.2.7 on 2025-10-16 08:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favoris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "favoris",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterestCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=120)),
            ],
            options={
                "db_table": "interest_center",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "module",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PossibleChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "possible_choice",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Quizz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("correct_answer", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "quizz",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "result",
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("registration_date", models.DateField()),
            ],
            options={
                "db_table": "user",
                "ordering": ["-registration_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-publish_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="article",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="theme",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=300),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["theme"], name="article_theme_615c57_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-publish_date"], name="article_publish_de2576_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="article",
            table="article",
        ),
        migrations.AddField(
            model_name="favoris",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoris",
                to="core.article",
            ),
        ),
        migrations.AddField(
            model_name="favoris",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoris",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(fields=["title"], name="module_title_1dd16c_idx"),
        ),
        migrations.AddField(
            model_name="quizz",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizz",
                to="core.module",
            ),
        ),
        migrations.AddField(
            model_name="possiblechoice",
            name="quizz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choix_possibles",
                to="core.quizz",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="core.module",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="user_email_7bbb4c_idx"),
        ),
        migrations.AddField(
            model_name="result",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="core.user",
            ),
        ),
        migrations.AddField(
            model_name="interestcenter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest_center",
                to="core.user",
            ),
        ),
        migrations.AddIndex(
            model_name="favoris",
            index=models.Index(
                fields=["user", "article"], name="favoris_user_id_c7d4c3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="favoris",
            constraint=models.UniqueConstraint(
                fields=("user", "article"), name="uniq_favoris_user_article"
            ),
        ),
        migrations.AddIndex(
            model_name="quizz",
            index=models.Index(fields=["module"], name="quizz_module__b5f558_idx"),
        ),
        migrations.AddIndex(
            model_name="possiblechoice",
            index=models.Index(fields=["quizz"], name="possible_ch_quizz_i_70acf2_idx"),
        ),
        migrations.AddConstraint(
            model_name="possiblechoice",
            constraint=models.UniqueConstraint(
                fields=("quizz", "choice"), name="uniq_quizz_choice"
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["user", "module"], name="result_user_id_150fad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="result",
            constraint=models.UniqueConstraint(
                fields=("user", "module"), name="uniq_result_user_module"
            ),
        ),
        migrations.AddIndex(
            model_name="interestcenter",
            index=models.Index(fields=["theme"], name="interest_ce_theme_75af1b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="interestcenter",
            unique_together={("user", "theme")},
        ),
    ]
