# Generated by Django 5.2.7 on 2025-10-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_favoris_interestcenter_module_possiblechoice_quizz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(unique=True),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-created_at"], name="article_created_06aad0_idx"
            ),
        ),
    ]
