# Generated by Django 5.2.7 on 2025-10-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_article_url_article_article_created_06aad0_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="url_nn",
            field=models.URLField(
                unique=True, null=False, default="http://placeholder.invalid"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="url_nn",
            field=models.URLField(unique=True, null=False),
        ),
    ]
