# Generated by Django 5.2.7 on 2025-10-21 22:39

from django.db import migrations


def copy_url_to_url_nn(apps, schema_editor):
    Article = apps.get_model("core", "Article")
    # Sécurité: on refuse s'il reste un NULL (ça éviterait un NOT NULL cassé)
    if Article.objects.filter(url__isnull=True).exists():
        raise RuntimeError("URLs NULL détectées: corriger avant le backfill.")
    # Copie
    for a in Article.objects.all().only("id", "url"):
        a.url_nn = a.url
        a.save(update_fields=["url_nn"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_url_nn"),
    ]

    operations = [
        migrations.RunPython(copy_url_to_url_nn, migrations.RunPython.noop),
    ]
