# Generated by Django 5.2.7 on 2025-10-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_backfill_url_nn"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="url"),
        migrations.RenameField(model_name="article", old_name="url_nn", new_name="url"),
    ]
