# Generated by Django 5.2.7 on 2025-11-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_feedsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
